package com.vampyreworld.w2t.sharedui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColorScheme(
    val white: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val info: Color,
    val neutral: Color,
    val shadow: Color,
    val bgSecondary: Color,
    val bgCool: Color,
    val primary100: Color,
    val primary80: Color,
    val primary60: Color,
    val primary40: Color,
    val primary20: Color,
    val primary10: Color,
    val primary5: Color,
    val primary15: Color,
    val dark: Color,
    val dark20: Color,
    val dark40: Color,
    val dark10: Color,
    val dark60: Color,
    val white100: Color,
    val white80: Color,
    val white60: Color,
    val white40: Color,
    val white20: Color,
    val white10: Color,
    val white5: Color,
    val naturalwhite100: Color,
    val naturalWhite80: Color,
    val naturalwhite60: Color,
    val naturalWhite40: Color,
    val naturalWhite20: Color,
    val naturalWhite15: Color,
    val naturalwhite10: Color,
    val naturalWhite5: Color,
    val black: Color,
    val black100: Color,
    val black80: Color,
    val black60: Color,
    val black40: Color,
    val black20: Color,
    val black15: Color,
    val black10: Color,
    val black5: Color,
    val success100: Color,
    val success80: Color,
    val success60: Color,
    val success40: Color,
    val success20: Color,
    val success10: Color,
    val success5: Color,
    val warning100: Color,
    val warning80: Color,
    val warning60: Color,
    val warning40: Color,
    val warning20: Color,
    val warning10: Color,
    val warning5: Color,
    val error100: Color,
    val error80: Color,
    val error60: Color,
    val error40: Color,
    val error20: Color,
    val error10: Color,
    val error15: Color,
    val error5: Color,
   val highText: Color,
    val lowText: Color,
    val secondary: Color,
    val greenBlue: Color,
    val greenBoarder: Color,
    val blueFill: Color,
    val lightBlue100: Color,
    val purple: Color,
    val red: Color,
    val orange: Color,
    val orange2: Color,
    val grayDeep: Color,
    val gray: Color,
    val messageBackground: Color,
    val messageStateColor: Color,
    val grayBorderColor: Color,
    val bgLight: Color,
    val transparent: Color,
    val unspecified: Color,
    val gradientBlue: Color,
    val blue: Color,
    val brightRed: Color,
)

val LightAppColors = AppColorScheme(
    white = white100,
    success = Success100,
    warning = Warning100,
    error = error100,
    info = InfoLight,
    neutral = NaturalWhite100,
    lowText = lowText,
    orange = Orange,
    orange2 = Orange2,
    grayDeep = GrayDeep,
    shadow = Shadow,
    bgSecondary = BgSecondary,
    bgCool = BgCool,
    primary100 = primary100,
    primary80 = Primary80,
    primary60 = Primary60,
    primary40 = Primary40,
    primary20 = Primary20,
    primary10 = Primary10,
    primary5 = Primary5,
    primary15 = Primary15,
    dark = Dark,
    dark20 = dark20,
    dark40 = dark40,
    dark10 = Dark10,
    dark60 = dark60,
    white100 = white100,
    white80 = White80,
    white60 = white60,
    white40 = White40,
    white20 = White20,
    white10 = white10,
    white5 = White5,
    naturalwhite100 = NaturalWhite100,
    naturalWhite80 = NaturalWhite80,
    naturalwhite60 = NaturalWhite60,
    naturalWhite40 = NaturalWhite40,
    naturalWhite20 = NaturalWhite20,
    naturalwhite10 = NaturalWhite10,
    naturalWhite5 = NaturalWhite5,
    black = black,
    black100 = black100,
    black80 = Black80,
    black60 = black60,
    black40 = Black40,
    black20 = Black20,
    black15 = Black15,
    black10 = black10,
    black5 = black5,
    success100 = Success100,
    success80 = Success80,
    success60 = Success60,
    success40 = Success40,
    success20 = Success20,
    success10 = Success10,
    success5 = Success5,
    warning100 = Warning100,
    warning80 = Warning80,
    warning60 = Warning60,
    warning40 = Warning40,
    warning20 = Warning20,
    warning10 = Warning10,
    warning5 = Warning5,
    error100 = error100,
    error80 = Error80,
    error60 = Error60,
    error40 = Error40,
    error20 = Error20,
    error15 = Error15,
    error10 = error10,
    error5 = Error5,
    highText = highText,
    secondary = Secondary,
    greenBlue = greenBlue,
    greenBoarder = greenBoarder,
    blueFill = blueFill,
    lightBlue100 = lightBlue100,
    purple = purple,
    red = red,
    gray = Gray,
    messageBackground = MessageBackground,
    messageStateColor = MessageStateColor,
    grayBorderColor = GrayBorderColor,
    bgLight = BgLight,
    naturalWhite15 = NaturalWhite15,
    transparent = Transparent,
    unspecified = Unspecified,
    gradientBlue = GradientBlue,
    blue = Blue,
    brightRed = BrightRed
)

val DarkAppColors = AppColorScheme(

    white = black100,
    success = Success100,
    warning = Warning100,
    error = error100,
    info = InfoLight,
    neutral = Dark,
    lowText = lowText,
    orange = Orange,
    orange2 = Orange2,
    grayDeep = GrayDeep,
    shadow = Shadow,
    bgSecondary = surfaceContainerDark,
    bgCool = surfaceContainerHighDark,

    primary100 = primary100,
    primary80 = Primary80,
    primary60 = Primary60,
    primary40 = Primary40,
    primary20 = Primary20,
    primary10 = Primary10,
    primary5 = Primary5,
    primary15 = Primary15,

    dark = NaturalWhite100,
    dark20 = NaturalWhite20,
    dark40 = NaturalWhite40,
    dark10 = NaturalWhite10,
    dark60 = NaturalWhite60,

    white100 = black100,
    white80 = Black80,
    white60 = black60,
    white40 = Black40,
    white20 = Black20,
    white10 = black10,
    white5 = black5,

    naturalwhite100 = black100,
    naturalWhite80 = Black80,
    naturalwhite60 = black60,
    naturalWhite40 = Black40,
    naturalWhite20 = Black20,
    naturalwhite10 = black10,
    naturalWhite5 = black5,

    black = NaturalWhite100,
    black100 = NaturalWhite100,
    black80 = NaturalWhite80,
    black60 = NaturalWhite60,
    black40 = NaturalWhite40,
    black20 = NaturalWhite20,
    black15 = NaturalWhite15,
    black10 = NaturalWhite10,
    black5 = NaturalWhite5,

    success100 = Success100,
    success80 = Success80,
    success60 = Success60,
    success40 = Success40,
    success20 = Success20,
    success10 = Success10,
    success5 = Success5,

    warning100 = Warning100,
    warning80 = Warning80,
    warning60 = Warning60,
    warning40 = Warning40,
    warning20 = Warning20,
    warning10 = Warning10,
    warning5 = Warning5,

    error100 = error100,
    error80 = Error80,
    error60 = Error60,
    error40 = Error40,
    error20 = Error20,
    error15 = Error15,
    error10 = error10,
    error5 = Error5,

    highText = white100,

    secondary = Secondary,

    greenBlue = greenBlue,
    greenBoarder = greenBoarder,
    blueFill = blueFill,

    lightBlue100 = primaryContainerDark,

    purple = purple,
    red = red,

    gray = outlineDark,

    messageBackground = customColor1ContainerDark,
    messageStateColor = customColor1Dark,

    grayBorderColor = outlineVariantDark,

    bgLight = backgroundDark,

    naturalWhite15 = NaturalWhite15,

    transparent = Transparent,
    unspecified = Unspecified,

    gradientBlue = inversePrimaryDark,

    blue = customColor3Dark,

    brightRed = error100
)
val LocalAppColorScheme = staticCompositionLocalOf {
    DarkColorScheme
    LightColorScheme
    DarkAppColors
    LightAppColors
}

val LightColorScheme = lightColorScheme(
    primary = primary100,
    secondary = Secondary,
    tertiary = Primary60,
    background = NaturalWhite100,
    surface = white100,
    onPrimary = white100,
    onSecondary = white100,
    onTertiary = White80,
    onBackground = black100,
    onSurface = black100,
    error = error100,
    errorContainer = Error80,
    onError = white100,
    surfaceVariant = white100
)

val DarkColorScheme = darkColorScheme(
    primary = primary100,
    secondary = customColor1Dark,
    tertiary = customColor2Dark,

    background = backgroundDark,
    surface = surfaceContainerDark,

    onPrimary = white100,
    onSecondary = white100,
    onTertiary = black100,

    onBackground = white100,
    onSurface = white100,

    error = errorContainerDarkMediumContrast,
    errorContainer = error100,
    onError = white100,

    surfaceVariant = surfaceContainerHighDark
)